# Generated by Django 5.1.1 on 2024-10-18 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('image', models.ImageField(blank=True, upload_to='media')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('position', models.IntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_tool.board')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=7)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_tool.project')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_tool.project'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=6)),
                ('story_points', models.IntegerField()),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_tool.list')),
            ],
        ),
        migrations.AddConstraint(
            model_name='list',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 0)), name='position_gte_0'),
        ),
        migrations.AlterUniqueTogether(
            name='list',
            unique_together={('board', 'title')},
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.CheckConstraint(condition=models.Q(('color__regex', '^#[A-Fa-f0-9]{6}$')), name='valid_hex_color'),
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('project', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('project', 'title')},
        ),
    ]
