# Generated by Django 5.1.1 on 2024-10-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_tool', '0004_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=6),
        ),
    ]
