# Generated by Django 5.1.1 on 2024-10-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_tool', '0006_task_labels_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
