# Generated by Django 5.1.1 on 2024-10-21 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_tool', '0009_alter_project_created_at'),
    ]

    operations = [
    ]
